Add ArduinoSpoof.h
RoboticsClubAtUCDavis/micromouse pull request #51
Opened 2017-03-09 21:02 UTC by blhough

spoofs the common arduino functions so they can be compiled on desktop

2017-03-09 21:25 UTC, ids1024 requested changes
When I try to build with this using `-include`, it results in "multiple definition" errors. Perhaps the implementations should be moved to a `.cpp` file?

2017-03-09 21:25 UTC, ids1024 commented on ArduinoSpoof.h
> +#ifdef VERBOSE_ARDUINO
If `VERBOSE_ARDUINO` is not set, these functions result in `unused parameter` errors.

2017-03-09 21:25 UTC, ids1024 commented on ArduinoSpoof.h
> +#define verbose_print(str) std::cout << str << std::endl;
The macro isn't used

2017-03-10 02:02 UTC, blhough commented
Requested changes addressed. https://github.com/RoboticsClubAtUCDavis/micromouse/pull/51/commits/8fc87ab8c9693a205b19bebde0cd752bb21f2a9e

2017-03-10 04:32 UTC, ids1024 commented
You haven't addressed the "multiple definition" errors when building with `-include`.

2017-03-10 07:12 UTC, blhough commented
Are you talking about when you build for the Teensy?

2017-03-10 07:41 UTC, blhough commented
I changed the #ifndef to something that becomes defined automatically when building on teensy vs having to manually define it in the main file.

2017-03-10 15:35 UTC, ids1024 commented
If this header is included in more than one .cpp file (I think it's best to include it everywhere with `-include` to match the behavior of the Arduino/Teensy standard library), it will fail to link, because the functions are defined multiple times.

2017-03-10 17:33 UTC, blhough commented
I'm kinda confused by what you're saying. Is the pragma once not working? Or are you including the file before the Teensy files?

2017-03-10 18:44 UTC, ids1024 commented
Pragma once only means the header will be included once in each compilation unit (.cpp file). But each .o will have a separate definition of each function, causing errors when they are linked together.

2017-03-10 21:15 UTC, blhough commented
Okay how about now?I have successful compiled this when including it in multiple files and on the Teensy.

Also renamed to Arduino.h because on the Teensy `#include<Arduino.h>` is required in files other than main.
When compiling for the Teensy, this file will not be in the directory checked by the Arduino compiler so instead it will include the normal version.

2017-03-10 21:47 UTC, ids1024 commented
Including the header in two random files (`Maze.cpp` and `Direction.cpp`) results in these errors: https://gist.github.com/6a91518ef15e48c8b40764a25d622b98

The solution to that would be to only declare the functions in the header, and define them in a `.cpp` header. Do you not get similar errors in Visual Studio? Perhaps it's because scons is building intermediate `.o` files before linking? Anyway, a seperate .cpp file is the correct way to do this.

(Also you're missing a `#include <stdio.h>`)

2017-03-10 22:06 UTC, blhough commented
Ohh okay, I made the functions static to prevent multiple definitions

2017-03-10 22:21 UTC, ids1024 commented
This results in "unused function" errors. Should I just disable that warning/error?

Also, `srandom` is an issue on Linux; libc provides a function with that name, which again prevents compilation. (There's also a `random` function, but that isn't an issue, since it takes different arguments).

I don't know how best to deal with that. Perhaps rename the function to `_arduino_srandom` (or similar) and then `#define srandom _arduino_srandom`. Although that's not ideal...

2017-03-10 22:36 UTC, blhough commented
Okay I decided not to be lazy and moved the definitions to a cpp. Maybe that will fix the not used warning idk? If not it will need to be suppressed.

I also removed `srandom` because arduino also has `randomSeed` which does the same thing

2017-03-10 22:39 UTC, ids1024 approved these changes

2017-03-10 22:40 UTC, merged